### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by epoxa** [dfcook/vue-webpack4-template#6]
```
git clone git@github.com:dfcook/vue-webpack4-template.git && cd vue-webpack4-template
npm install
npm run dev
```
Gives me the following error:
```
> vue-webpack-4@1.0.0 dev /www/vue-webpack4-template
> webpack-dev-server --progress --config build/webpack.config.dev.js

 10% building 1/1 modules 0 activeevents.js:183                              
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1517:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)

npm ERR! Linux 4.15.0-42-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! vue-webpack-4@1.0.0 dev: `webpack-dev-server --progress --config build/webpack.config.dev.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-webpack-4@1.0.0 dev script 'webpack-dev-server --progress --config build/webpack.config.dev.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-webpack-4 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --progress --config build/webpack.config.dev.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-webpack-4
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-webpack-4
npm ERR! There is likely additional logging output above.
```

**Comment by dfcook** [comment]
Hi, that looks like you have something else running on that port. If you want to use a different port you can specify this in ```build/webpack.config.dev.js```.

`const PORT = 8080`

Change this value and try running again.

**Comment by epoxa** [comment]
Thanks, Daniel. 
That was really silly :)
